version: '3.9'
services:
  db:
    image: 10.0.3.47:5000/mypois-db:latest
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  phpadmin:
    image: phpmyadmin/phpmyadmin:5.0.4
    depends_on:
      - db
    ports:
      - 8080:80
    restart: always
  mypois-app:
    image: 10.0.3.47:5000/mypois-app:latest
    depends_on:
      - db
    environment:
      ENV_DB_HOST: db
    ports:
      - 9080:9080
      - 9443:9443
    restart: always